private_key: CaY5iCkYtN7DqXdiYK1BvmGrQuaSA4Tl4bEk9my0jc0=

secret: U6rct6fv89jkjb8hHJJ95bKOjfodfu8KMBYf059ng909nIhnJNd

default_admin:
  name: default_admin
  password: default_password

app_name: MyTestApp

database:
  host: db
  port: 5432
  user: postgres
  password: postgres
  database: sanic_test